### ISSUE TITLE
Issue with Free Update Cost

### ISSUE THREAD

**Issue by Pokter** [Aerin-the-Lion/MGT2---Free-Update-Rebalancer#2]
There seem to be an issue with the cost of the free update in the current build of MGT2 using the free update rebalancer mod.
The cost for the update is shown fixed with the value of 1,065,353,216 no matter the choosen content.
This behavior can be replicated on multiple saves and is also showing with free-update-rebalancer as only mod installed.

![image](https://github.com/Aerin-the-Lion/MGT2---Free-Update-Rebalancer/assets/157424388/30c201ac-c927-4ebb-8930-7519ad84a2eb)

When looking at the debug console it seems that the cost calculation itself is working fine (I've switched content and the value printed was changing in a consistent way).

![image](https://github.com/Aerin-the-Lion/MGT2---Free-Update-Rebalancer/assets/157424388/cc8a87a4-4672-4eb5-b036-77eb483ff772)

The used version of BepInEx is 5.4.21.0

If you need additional information I'm happy to help.

**Comment by Aerin-the-Lion** [comment]
I suppose your MGT2 environment hasn't had the fix patch installed yet.

From what I know, this is a known bug in the older version of Mono Mod.
You should try installing the latest version of Mono Mod or this fix patch into your BepInEx folder.


BepInEx(x84) fix patch(MMTestFix.Zip)
https://github.com/BepInEx/BepInEx/issues/458
https://github.com/BepInEx/BepInEx/files/9275584/MMTestFix.zip

**Comment by Pokter** [comment]
The MM patch is solving the issue, thanks for the quick reply.
